# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cc2f337104529648f6e6125cab9913cc7715043a5032ab6866b53aa1d573872740e00dad298df25f0b4def71345b92db7026abd3931ae9830f21591b4cc6278

test:
  secret_key_base: 25d930636911f73c65f0f49d885ebac38c23fd1e905f550a0338c31600c24cb2ce4ca32f2898b8e3481a5dac2b5c304949feced1625b647623dae1a351ff9a46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
