# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e816264820ecfc861792b2d3e5f72873e7e6da8ff8a97f1f771999999562be439d389dfea5e91bbcfa68ac41e5ee9d3874b0bf21f25e60984868da2638d0e85

test:
  secret_key_base: ef15b24db49b2f5b2a9acd5551f963de586c63c853056650860f4e724df7ee605e1101be4863f042d6e03251cd7fdf5178e35bd1a7a3dc00cfd6160854e3f9c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
