# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 170673edbc9b0a9a3365633ec30219645ea428b1bfdecc155f3d288c6e7b1c1afffd3868621caea7c5491ee4ec45db301095f8649822e87d9a6af3cf4da64614

test:
  secret_key_base: 1285629d56919677855157e49d1baf064ab43a22660670e975f56877cbce70dfacb9c9ca9490612498fce1e5e4fea5784c79ebdcef395f14224841f7bb07f0e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
